### ISSUE TITLE
CSS: Font ICON 在部分设备中不显示

### ISSUE THREAD

**Issue by minwe** [amazeui/amazeui#193]
@chuanze
> 图标显示不出来，红米手机，海豚浏览器

[@yi1i](http://www.baidu.com/p/yi1i)
> Font Awesome在酷派 9190L手机中的微信浏览器里图标显示不出，在手机浏览器中倒能显示

 [@李帖](http://t.qq.com/Kistler5)
> 目前最新版本，在android 版 微信内是不显示图标的。不知道伙伴们是否有遇到类似问题。

via @chuanze
> 修改一下css代码就可以了。将 `[class*='am-icon-']` 改为
```css
[class*='am-icon-'] {
  display: inline-block;
  font: normal normal normal 14px/1 FontAwesome;
  font-size: inherit;
  text-rendering: auto;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
```

**可能是这些浏览器内置的样式覆盖了 `font-family: "FontAwesome";`**

**Comment by mujiangze** [comment]
![screenshot_2015-01-19-14-16-33](https://cloud.githubusercontent.com/assets/876712/5796850/6814f0e0-9fea-11e4-8994-a3ea4a07e75c.png)
红米note还是不显示。。。

**Comment by mujiangze** [comment]
不引用amazeUI的样式，直接用fontawesome就能显示。

**Comment by Minwe** [comment]
@mujiangze 使用的微信？具体是什么版本的？

**Comment by mujiangze** [comment]
@Minwe 嗯，用的微信浏览器查看的，同事的vivo手机的微信也不行。尝试了很多网上的办法不行，后来把amazeUI.basic.css文件里的@font-face引入字体路径改成本地相对路径，（ {
font-family: 'FontAwesome';
src: url('../font/fontawesome-webfont.eot?v=4.2.0');）本地font文件夹里放相对应的4.2版本的字体文件
就正常显示了

**Comment by mujiangze** [comment]
@Minwe 
![default](https://cloud.githubusercontent.com/assets/876712/5798273/db5d3b64-a000-11e4-822d-a56e9bc6261b.png)
微信都是最新的版本，因为之前做项目用到就是在微信里面某些机型（比如我的这个）不显示，在自带浏览器里面显示正常。

**Comment by qixiaobo** [comment]
nexus s 和红米note相同现象

**Comment by Linrstudio** [comment]
红米手Q不显示 icon

**Comment by Linrstudio** [comment]
注意了，如果手Q或微信不是X5内核，可能部分安卓手机不显示 iconfont，可以理解为安卓的 webview BUG。

**Comment by minwe** [comment]
再次用以前有问题的酷派手机测试了一下，都能正常显示了。

应该是随着 QQ 和微信版本升级，webview 的 bug 已经修复，加上手机更新换代，我们就不再关注这个问题。

**Comment by tufei1995** [comment]
如果CSS是其他网站引入的，比如CDN，那么字体文件就会存在跨站请求的问题，所以字体不会显示

**Comment by meicj** [comment]
问题：在酷派 8730L下，所有字体图标不能正常显示，暂未找到有效方法

测试机型：酷派 8730L
系统版本：安卓4.3
软件：自带浏览器

http://www.w3cmark.com/demo/iconfont.html 页面效果截屏（所有方式的图标不能显示）：
![image](https://cloud.githubusercontent.com/assets/10281234/16684509/01521334-4538-11e6-9dac-48be3c771075.png)

http://amazeui.org/css/icon?_ver=2.x 页面效果截屏（所有图标不能显示）：
![image](https://cloud.githubusercontent.com/assets/10281234/16684485/dfbaa4a2-4537-11e6-948b-f1b9140e7e7f.png)

包括上面@chuanze 说的方法使用 `font: normal normal normal 14px/1 FontAwesome;` 也不能正常显示

**Comment by minwe** [comment]
@meicj 

你可以测试一下 http://t.amazeui.org/kitchen-sink/#/icon?_k=bxrqbc

以及 http://getbootstrap.com/components/#glyphicons，如果都不能显示，那就是硬伤了。

**Comment by meicj** [comment]
@minwe 

感谢你的回复，经过一番折磨昨天终于解决了这个问题， 并 [整理了一篇文章](https://meicj.com/post/iconfont-compatible-issue-on-android.html#end) 说明这个问题。

再次感谢。

**Comment by minwe** [comment]
@meicj 

推演测试得很仔细、完整，通过对比研究找到问题的思路也值得学习。

原来遇到类似问题的同学可以参考。

根据 https://css-tricks.com/snippets/css/using-font-face/ 上的描述：

```css
@font-face {
  font-family: 'MyWebFont';
  src: url('myfont.woff2') format('woff2'),
       url('myfont.woff') format('woff'),
       url('myfont.ttf') format('truetype');
}
```

上面的设置支持到 Safari 3+，svg 格式只是为了 iOS 4.1- 的设备，基本可以忽略了，所以 Amaze UI 在以后的更新中打算直接删除 svg 设置。

另外，CIU 上的数据只针对 Android 原厂的浏览器及 WebView，对国内某些厂商进行破坏性二次开发的 UA，显然是不准确的。这个问题本质上还是酷派进行二次开发以后的产生的 bug。
