### ISSUE TITLE
Bug：安卓手机手机QQ或者微信打开页面，文字溢出点点拦不住文字

### ISSUE THREAD

**Issue by wangwenjie1314** [amazeui/amazeui#416]
安卓手机手机QQ或者微信打开页面的时候，
有文字溢出... 但是多出的文字没有被隐藏住，还是展示出来了，栏目列表展示时，左文字 右日期时最明显

**Comment by wangwenjie1314** [comment]
可能我说了 你们不太理解；
上图说明问题
![Stated Clearly Image](http://ebook.u.qiniudn.com/11112121312.png)
![Stated Clearly Image](http://ebook.u.qiniudn.com/2212121.png)
![Stated Clearly Image](http://ebook.u.qiniudn.com/32321213.png)

``` html
<div data-am-widget="list_news" class="am-list-news am-list-news-default am-text-sm">
  <div class="am-list-news-bd">
    <ul class="am-list">
      <li class="am-g am-list-item-dated">
        <a href="##" class="am-list-item-hd">我很囧，你保重....晒晒旅行中的那些囧！</a>
        <span class="am-list-date">2013-09-18</span>
      </li>
      <li class="am-g am-list-item-dated">
        <a href="##" class="am-list-item-hd">我最喜欢的一张画</a>
        <span class="am-list-date">2013-10-14</span>
      </li>
      <li class="am-g am-list-item-dated">
        <a href="##" class="am-list-item-hd">“你的旅行，是什么颜色？” 晒照片，换北欧梦幻极光之旅！</a>
        <span class="am-list-date">2013-11-18</span>
      </li>
      <li class="am-g am-list-item-dated">
        <a href="##" class="am-list-item-hd">我很囧，你保重....晒晒旅行中的那些囧！</a>
        <span class="am-list-date">2013-09-18</span>
      </li>
      <li class="am-g am-list-item-dated">
        <a href="##" class="am-list-item-hd">我最喜欢的一张画</a>
        <span class="am-list-date">2013-10-14</span>
      </li>
      <li class="am-g am-list-item-dated">
        <a href="##" class="am-list-item-hd">“你的旅行，是什么颜色？” 晒照片，换北欧梦幻极光之旅！</a>
        <span class="am-list-date">2013-11-18</span>
      </li>
      <li class="am-g am-list-item-dated">
        <a href="##" class="am-list-item-hd">我很囧，你保重....晒晒旅行中的那些囧！</a>
        <span class="am-list-date">2013-09-18</span>
      </li>
      <li class="am-g am-list-item-dated">
        <a href="##" class="am-list-item-hd">我最喜欢的一张画</a>
        <span class="am-list-date">2013-10-14</span>
      </li>
      <li class="am-g am-list-item-dated">
        <a href="##" class="am-list-item-hd">“你的旅行，是什么颜色？” 晒照片，换北欧梦幻极光之旅！</a>
        <span class="am-list-date">2013-11-18</span>
      </li>
    </ul>
  </div>
```

**Comment by wangwenjie1314** [comment]
我现在采用了一种强制性写法，但是也有问题（文字被切现象）：
妹子UI 1.0x

``` css
.am-list .am-list-item-dated a {
  padding-right: 80px;
  display: block;
  word-wrap: normal;
  /* for IE */
  text-overflow: ellipsis;
  white-space: nowrap;
  overflow: hidden;
}
````

``` css
/*上面的基础上修改如下*/
.am-list .am-list-item-dated a{padding-right: 0;margin-right:8rem;color:#666}
````

**Comment by Minwe** [comment]
手机型号、系统以及版本、微信/QQ 的版本分别是啥？

**Comment by wangwenjie1314** [comment]
测试页面：http://wangwenjie1314.github.io/views/tbcm/companyNews.html
——————————————
手机 小米2s
安卓版本4.1.1
微信版本 最新
手机QQ 版本最新
——————————————

**Comment by Minwe** [comment]
你把 padding 和 margin 改为原来的值，加上下面的样式试一下：

```css
.am-list-item-hd {
  width: 100%;
}
```
