### ISSUE TITLE
在移动端显示代码的问题

### ISSUE THREAD

**Issue by dowhilenet** [amazeui/amazeui#816]
你好，我十分高兴在国内有着这么好用的库。

我有一个问题想请教一下。在移动端显示代码的时候，如果代码过长的就超出了屏幕的外边，需要移动屏幕才可以看全。有没有什么好的办法，能让代码自动换行呢。

由于对css不是特别熟悉，希望能得到好的解决。

谢谢 :]

**Comment by minwe** [comment]
百度关键词【css 强制换行】

```css
code {
  white-space: normal;
}
```
