### ISSUE TITLE
slider d3（标题+缩略图导航）手机上缩略图会平铺

### ISSUE THREAD

**Issue by bajian** [amazeui/amazeui#839]
直接复制示例的代码
电脑可以正常显示，UC微信都不能正常显示
[链接](https://rawgit.com/bajian/AMTest/master/banner2.html)

**Comment by minwe** [comment]
使用了 Flexbox，可能浏览器支持不太好。。
UC 和微信的版本是多少？

**Comment by bajian** [comment]
@minwe 
试了两个安卓机都不行 微信6.3.13、UC v10.9.4.728
IOS没问题

**Comment by minwe** [comment]
加上： 

```css
.am-slider-d3 .am-control-thumbs {
  display: table;
}

.am-slider-d3 .am-control-thumbs li {
  display: table-cell;
}
```

要想兼容安卓上各国阉浏览器和微信 ，只能用老的方法了……

**Comment by bajian** [comment]
@minwe 
UC可以了。，，但是微信里还是有问题：
首次展示没问题。切换的时候就跪了：
点击切换
![Screenshot](https://rawgit.com/bajian/AMTest/master/Screenshot_2016-02-29-11-17-42_com.tencent.mm.png)

滑动切换
![Screenshot](https://rawgit.com/bajian/AMTest/master/Screenshot_2016-02-29-11-18-32_com.tencent.mm.png)

**Comment by minwe** [comment]
再加下面的样式试试。

```css
.am-slider-d3 .am-control-thumbs li {
  display: table-cell;
  width: 1%;
}
```
