### ISSUE TITLE
tab的动画能不能修改?

### ISSUE THREAD

**Issue by mqliutie** [amazeui/amazeui#850]
## 问题描述

tab的动画能不能修改?

## 产生环境

- **设备：**  电脑
- **操作系统及版本：** mac pro 10.11.2 (15C50)
- **浏览器及版本：** chrome 49.0.2623.87 (64-bit)
- **演示地址：**  no

想把动画去掉,或者换一种动画,这个动画文本从框外进来,看起来不是很舒服

**Comment by minwe** [comment]
```css
.am-tab-panel {
  transition: none;
}
```
