### ISSUE TITLE
Button-group在微信中没有效果

### ISSUE THREAD

**Issue by ftchao** [amazeui/amazeui#856]
## 问题描述

Button-group在微信中没有效果

## 产生环境

- **设备：**（手机、平板等移动设备时填写此项）手机
- **操作系统及版本：** 微信
- **浏览器及版本：** 
- **演示地址：**  http://ebay.ftchao.com/?#!/register

## 代码片段
```
<form class="am-form">
  <fieldset>
  	<h2 class="rg-title">新用户注册</h2>

    <div class="am-form-group">
      <div class="am-btn-group am-btn-group-justify">
        <input type="text" class="" id="doc-ipt-email-1" placeholder="请输入手机号">
        <a type="button" class="am-btn am-btn-primary">获取短信验证码</a>
      </div>
    </div>

    <div class="am-form-group">
        <input type="password" class="" id="doc-ipt-pwd-1" placeholder="请设置6-20位登录密码">
    </div>

    <div class="am-form-group">
        <input type="text" class="" id="doc-ipt-pwd-1" placeholder="请输入短信验证码">
    </div>

    <button type="bottom" class="am-btn am-btn-primary am-btn-block">注册</button>

  </fieldset>
</form>
```

**Comment by minwe** [comment]
加入：

```css
.am-btn-group-justify {
  display: table;
  table-layout: fixed;
  border-collapse: separate;
}

.am-btn-group-justify > .am-btn,
.am-btn-group-justify > .am-btn-group {
  display: table-cell;
  width: 1%;
}
```
