### ISSUE TITLE
header固定后手机浏览页面卡顿问题

### ISSUE THREAD

**Issue by yufanmn** [amazeui/amazeui#863]
## 问题描述
http://amazeui.org/examples/admin-table.html
http://amazeui.org/examples/admin-index.html
以上两个示例页面在手机端浏览时，页面高度超出屏幕高度，导致页面上下滚动时非常不流畅。
## 产生环境

- **设备及型号：iPhone 6 Plus
- **操作系统及版本：ios9.3.1
- **浏览器及版本：safari
- **演示地址：
http://amazeui.org/examples/admin-table.html
http://amazeui.org/examples/admin-index.html
## 复现步奏

1.打开页面
2.滚动右侧页面

**Comment by yufanmn** [comment]
也不一定是卡，就是滑动一下惯性滚动的那个效果没了，这是什么原因呢？

**Comment by minwe** [comment]
```css
.admin-content,
.admin-sidebar {
  -webkit-overflow-scrolling: touch;
}
```

非 HTML 上的滚动条 iOS Safari 默认不开启平滑滚动。
