### ISSUE TITLE
页面顶部固定时，手机端页面中使用popup，会被遮住

### ISSUE THREAD

**Issue by ww380459000** [amazeui/amazeui#893]

**Comment by minwe** [comment]
这种交互就是这样设计的，原生应用里也是这样的。

如果有特殊需求，请自行添加以下样式覆盖。

http://bin.amazeui.org/kikelanuga/edit?html,output

```css
#my-popup {
  top: 50px;
}
```
