### ISSUE TITLE
Amaze UI 模态窗口 Popup 如何取消弹出特效 或者改变弹出方式？

### ISSUE THREAD

**Issue by dabing69221** [amazeui/amazeui#908]
问题描述

  Amaze UI 模态窗口 Popup 弹出方式如何取消特效，现在一点弹出，Popup窗口老是从下往上弹出，弄得手机一卡一卡的，如何设置取消这种弹出方式，或者改变弹出方式也行
![Uploading QQ截图20160811091057.png…]()

**Comment by dabing69221** [comment]
@minwe

**Comment by minwe** [comment]
```css
.am-popup {
  transition: initial !important;
}
```

**Comment by dabing69221** [comment]
我试试

**Comment by dabing69221** [comment]
设置之后 propup 弹出窗口 还是会 从下往上弹出，关闭窗口的时候 会从上往下关闭，有没有解决方案，实现类似 Alert 模态窗口 的关闭方式？

**Comment by minwe** [comment]
```css
.am-popup {
  -webkit-transition: none !important;
  transition: none !important;
}
```
