### ISSUE TITLE
Bug: WebKit引擎的浏览器下默认字体最小为12px

### ISSUE THREAD

**Issue by zhihuihu** [amazeui/amazeui#912]
WebKit引擎的浏览器下默认字体最小为12px，如果设置高为1rem那么高就是12px并不是官方的10px，请问有什么好的解决方法

**Comment by minwe** [comment]
这个已经失效：

```css
* {
  -webkit-text-size-adjust: none;
}
```

如果实在需要的话只能通过 `scale` 来实现：

http://mjj.logdown.com/posts/39967-set-css-font-size-less-than-12px-in
